apiVersion: v1
kind: Service
metadata:
  labels:
    name: kibana
  name: kibana
spec:
  ports:
  - name: kibana
    protocol: TCP
    port: 5601
  selector:
    name: kibana
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: tools
  annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/affinity: "cookie"
      ingress.kubernetes.io/session-cookie-name: "route"
      ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - host: kibana.tools.t8i7.net
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
